# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=256, verbose_name='Model uuid')),
                ('path', models.CharField(max_length=256, verbose_name='Path to original model')),
                ('pathInFittingService', models.CharField(max_length=256, verbose_name='Path to model in fitting service')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=256, verbose_name='Path to original scan')),
                ('pathInFittingService', models.CharField(max_length=256, verbose_name='Path to scan in fitting service')),
            ],
        ),
    ]
