# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0002_auto_20170203_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.AlterField(
            model_name='scan',
            name='path',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Path to original scan'),
        ),
    ]
