# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0003_auto_20170203_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='pathInFittingService',
            new_name='path_in_fitting_service',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='pathInFittingService',
            new_name='path_in_fitting_service',
        ),
    ]
