# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0004_auto_20170203_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('path_in_fitting_service', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, unique=True)),
                ('base_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='path',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='path_in_fitting_service',
        ),
        migrations.AddField(
            model_name='scan',
            name='id',
            field=models.CharField(default='lol', max_length=256, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='original_left_foot_path',
            field=models.CharField(default='lolo', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='original_right_foot_path',
            field=models.CharField(default='lol;', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='path_left_foot_in_fitting_service',
            field=models.CharField(default='sdff', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='path_right_foot_in_fitting_service',
            field=models.CharField(default='ds', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='scanner',
            field=models.CharField(default='fddfsdfs', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='type',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
