# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0005_auto_20170203_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='path',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
