# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0007_auto_20170206_0759'),
    ]

    operations = [

    ]
