# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0009_auto_20170206_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
