# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0010_auto_20170207_1238'),
    ]

    operations = [

    ]
