# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0012_auto_20170207_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
