# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0013_delete_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('scan_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=100)),
                ('value_for_left', models.CharField(max_length=100)),
                ('value_for_right', models.CharField(max_length=100)),
            ],
        ),
    ]
