# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0014_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='path_in_fitting_service',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
