# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0016_user_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_for_left',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_for_right',
            field=models.CharField(max_length=1000),
        ),
    ]
