# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0017_auto_20170222_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_scan_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
