# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0020_tempscan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
