# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0021_delete_scan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempScan',
            new_name='Scan',
        ),
    ]
