# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0022_auto_20170301_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_scan_id',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='scan_id',
            field=models.IntegerField(),
        ),
    ]
