# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0024_user_default_scan_id'),
    ]

    operations = [
        
    ]
