# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0025_compareresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_id', models.IntegerField()),
                ('scan_id', models.IntegerField()),
                ('compare_result', models.FloatField()),
                ('output_model', models.CharField(max_length=1000)),
            ],
        ),
    ]
