# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0026_auto_20170302_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compareresults',
            unique_together=set([('shoe_id', 'scan_id')]),
        ),
    ]
