# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0027_auto_20170309_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='path',
            field=models.CharField(max_length=1000),
        ),
    ]
