# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0029_auto_20170419_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLastProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
            bases=('fitting.last',),
        ),
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Product lasts',
                'verbose_name_plural': 'Product lasts',
            },
            bases=('fitting.product',),
        ),
        migrations.RenameField(
            model_name='last',
            old_name='attachatment',
            new_name='attachment',
        ),
        migrations.AddField(
            model_name='last',
            name='product',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='fitting.Product'),
            preserve_default=False,
        ),
    ]
