# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0030_auto_20170419_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompareResults',
            new_name='CompareResult',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.DeleteModel(
            name='ProductLastProxy',
        ),
        migrations.AlterModelOptions(
            name='productproxy',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
