# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0032_auto_20170420_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='size',
        ),
        migrations.AddField(
            model_name='user',
            name='sizes',
            field=models.ManyToManyField(to='fitting.Size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_scan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.Scan'),
        ),
    ]
