# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0033_auto_20170420_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='type',
            new_name='scan_type',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='original_left_foot_path',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='original_right_foot_path',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='path_left_foot_in_fitting_service',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='path_right_foot_in_fitting_service',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_scan_id',
        ),
        migrations.AddField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fitting.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='default_scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_scan', to='fitting.Scan'),
        ),
    ]
