# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import fitting.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0038_auto_20170420_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last',
            name='attachment',
            field=models.FileField(upload_to=fitting.models.attachment.gen_file_name),
        ),
        migrations.AlterField(
            model_name='scan',
            name='attachment',
            field=models.FileField(upload_to=fitting.models.attachment.gen_file_name),
        ),
    ]
