# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0039_auto_20170420_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='last',
            name='path',
        ),
    ]
