# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0040_remove_last_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresult',
            name='last',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.Last'),
        ),
        migrations.AlterUniqueTogether(
            name='compareresult',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='compareresult',
            name='scan',
        ),
    ]
