# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0041_auto_20170420_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareresult',
            name='scan_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scan_1', to='fitting.Scan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compareresult',
            name='scan_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_2', to='fitting.Scan'),
        ),
        migrations.AlterUniqueTogether(
            name='compareresult',
            unique_together=set([('last', 'scan_1', 'scan_2')]),
        ),
    ]
