# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0046_auto_20170421_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='value_for_left',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_for_right',
        ),
        migrations.AlterField(
            model_name='user',
            name='default_scans',
            field=models.ManyToManyField(blank=True, related_name='default_scans', to='fitting.Scan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='fitting.Size'),
        ),
    ]
