# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0047_auto_20170426_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Attribute',
            new_name='ScanAttribute',
        ),
        migrations.CreateModel(
            name='LastProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Last',
                'verbose_name_plural': 'Lasts',
                'proxy': True,
            },
            bases=('fitting.last',),
        ),
        migrations.AddField(
            model_name='lastattribute',
            name='last',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitting.Last'),
        ),
        migrations.AddField(
            model_name='lastattribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitting.User'),
        ),
    ]
