# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0048_auto_20170427_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastattribute',
            name='user',
        ),
    ]
