# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0049_remove_lastattribute_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'proxy': True,
            },
            bases=('fitting.scan',),
        ),
    ]
