# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0050_scanproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastattribute',
            name='best_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lastattribute',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lastattribute',
            name='left_limit_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lastattribute',
            name='right_limit_value',
            field=models.FloatField(default=0),
        ),
    ]
