# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0051_auto_20170428_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastattribute',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
