# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0052_auto_20170428_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='numeric_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
