# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0053_size_numeric_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresult',
            name='output_model',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='compareresult',
            name='scan_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_2', to='fitting.Scan'),
        ),
    ]
