# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import fitting.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0054_auto_20170502_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastAttributeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Last Attribute',
                'verbose_name_plural': 'Last Attributes',
                'proxy': True,
            },
            bases=('fitting.lastattribute',),
        ),
        migrations.AlterField(
            model_name='last',
            name='attachment',
            field=models.FileField(blank=True, upload_to=fitting.utils.gen_file_name),
        ),
        migrations.AlterField(
            model_name='scan',
            name='attachment',
            field=models.FileField(blank=True, upload_to=fitting.utils.gen_file_name),
        ),
    ]
