# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0055_auto_20170504_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastattribute',
            name='scan_attribute_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set([('size_type', 'value')]),
        ),
    ]
