# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0060_auto_20170508_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('CUSTOM', 'Undefined type'), ('FOOT', 'Foot'), ('LEFT_FOOT', 'Foot left'), ('RIGHT_FOOT', 'Foot right')], default='CUSTOM', max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('numeric_value', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set([('model_type', 'value')]),
        ),
        migrations.AddField(
            model_name='last',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.Size'),
        ),
        migrations.AddField(
            model_name='user',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='fitting.Size'),
        ),
    ]
