# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0062_remove_scanattribute_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='last',
            name='last_type',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scan_type',
        ),
        migrations.AddField(
            model_name='last',
            name='model_type',
            field=models.CharField(choices=[('CUSTOM', 'Undefined type'), ('FOOT', 'Foot'), ('LEFT_FOOT', 'Foot left'), ('RIGHT_FOOT', 'Foot right')], default='CUSTOM', max_length=64),
        ),
        migrations.AddField(
            model_name='scan',
            name='model_type',
            field=models.CharField(choices=[('CUSTOM', 'Undefined type'), ('FOOT', 'Foot'), ('LEFT_FOOT', 'Foot left'), ('RIGHT_FOOT', 'Foot right')], default='CUSTOM', max_length=64),
        ),
        migrations.DeleteModel(
            name='ModelType',
        ),
    ]
