# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import fitting.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0062_remove_scanattribute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attachment',
            field=models.FileField(blank=True, upload_to=fitting.utils.gen_file_name),
        ),
        migrations.AlterField(
            model_name='lastattribute',
            name='scan_attribute_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
