# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0063_auto_20170622_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareresult',
            name='output_model_3d',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
