# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0064_compareresult_output_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.IntegerField(default=1),
        ),
    ]
