# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 16:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0066_compareresult_output_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresult',
            name='output_difference',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
