# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0067_auto_20171030_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareVisualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_model', models.CharField(blank=True, max_length=1000)),
                ('output_model_3d', models.CharField(blank=True, max_length=1000)),
                ('last', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.Last')),
                ('scan_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_vis_1', to='fitting.Scan')),
                ('scan_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_vis_2', to='fitting.Scan')),
            ],
        ),
        migrations.RemoveField(
            model_name='compareresult',
            name='output_model',
        ),
        migrations.RemoveField(
            model_name='compareresult',
            name='output_model_3d',
        ),
        migrations.AlterField(
            model_name='compareresult',
            name='scan_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_res_1', to='fitting.Scan'),
        ),
        migrations.AlterField(
            model_name='compareresult',
            name='scan_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_res_2', to='fitting.Scan'),
        ),
        migrations.AlterUniqueTogether(
            name='comparevisualization',
            unique_together=set([('last', 'scan_1', 'scan_2')]),
        ),
    ]
