# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0068_auto_20171115_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparevisualization',
            name='output_model',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comparevisualization',
            name='output_model_3d',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
