# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0069_auto_20171117_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_id', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='else', max_length=256)),
                ('password', models.CharField(default='7kjfWVWcRN', max_length=256)),
                ('access', models.CharField(default='WEBDAV', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='size',
            name='numeric_value',
            field=models.IntegerField(verbose_name='ordering value'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='storage_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanners', to='fitting.StorageAccount'),
        ),
    ]
